### ISSUE TITLE
USER STORY: Queue preferences

### ISSUE THREAD

**Issue by Max9414** [Max9414/Agile-stuff#2]
As a **T&S team member** I can **select my preference for the queue** so that **I could get less stressed during the day**

# Acceptance Criteria

- Acceptance Criteria 1: Dropdown list of all the queues
- Acceptance Criteria 2: 3 preference options of decreasing likeability
- Acceptance Criteria 3: Eliminate chance of selecting twice the same queue

# Tasks

- [ ] Create dropdown list with all queues
- [ ] Capture employee name
- [ ] Save preferences in a server
- [ ] Eliminate the queue from the list if already selected
