### ISSUE TITLE
USER STORY: Update preferences

### ISSUE THREAD

**Issue by Max9414** [Max9414/Agile-stuff#3]
As a **T&S employee member** I can **change preferences to the queues I like** so that **I can have variations during my workday or in different weeks**

# Acceptance Criteria

- Acceptance Criteria 1: Button to modify already selected options
- Acceptance Criteria 2: Database update

# Tasks

- [ ] Create an update buttons for preferences
- [ ] Can add prefilled employee infos
- [ ] Update database with new preferences
