### ISSUE TITLE
USER STORY: Breaks preferences

### ISSUE THREAD

**Issue by Max9414** [Max9414/Agile-stuff#4]
As a **T&S employee member** I can **select preferences for breaks** so that **I could have more stability during my workday**

# Acceptance Criteria

- Acceptance Criteria 1: Break select time for am and pm
- Acceptance Criteria 2: Chance to have it randomised if no preferences
- Acceptance Criteria 3: Possibility to change preferences

# Tasks

- [ ] Add database for breaks preferences
- [ ] Add update buttons for future changes
- [ ] Check if there are other people already with the same preferences and inform user
- [ ] Adapt breaks to not have more than 2 people on short breaks at the same time

**Comment by Max9414** [comment]
This is completed

**Comment by Max9414** [comment]
It was just a closing test.
